# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/kersz/Documents/cv32e40p/cv32e40p.runs/synth_1/axi_subsystem.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {Synth 8-7129} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kersz/Documents/cv32e40p/cv32e40p.cache/wt [current_project]
set_property parent.project_path /home/kersz/Documents/cv32e40p/cv32e40p.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_repo_paths /home/kersz/Documents/cv32e40p/cv32e40p.ip_user_files/packages/core_axi [current_project]
update_ip_catalog
set_property ip_output_repo /home/kersz/Documents/cv32e40p/cv32e40p.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/kersz/Documents/cv32e40p/rtl/include
  /home/kersz/Documents/cv32e40p/bhv
  /home/kersz/Documents/cv32e40p/bhv/include
  /home/kersz/Documents/cv32e40p/sva
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/kersz/Documents/cv32e40p/programs/basic/basic.coe
read_verilog /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_common_cells/include/common_cells/registers.svh
set_property file_type "Verilog Header" [get_files /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_common_cells/include/common_cells/registers.svh]
read_verilog -library xil_defaultlib -sv {
  /home/kersz/Documents/cv32e40p/rtl/impl/axi_exit_dec.sv
  /home/kersz/Documents/cv32e40p/rtl/impl/axi_mm_ram.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv
  /home/kersz/Documents/cv32e40p/rtl/impl/clk_div.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/impl/core2axi.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_aligner.sv
  /home/kersz/Documents/cv32e40p/rtl/include/cv32e40p_pkg.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_alu.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_alu_div.sv
  /home/kersz/Documents/cv32e40p/rtl/include/cv32e40p_apu_core_pkg.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_apu_disp.sv
  /home/kersz/Documents/cv32e40p/rtl/impl/cv32e40p_axi.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_compressed_decoder.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_controller.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_core.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_cs_registers.sv
  /home/kersz/Documents/cv32e40p/rtl/include/cv32e40p_fpu_pkg.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_decoder.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_ex_stage.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_ff_one.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_fifo.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv
  /home/kersz/Documents/cv32e40p/rtl/fp/cv32e40p_fp_wrapper.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_hwloop_regs.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_id_stage.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_if_stage.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_int_controller.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_load_store_unit.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_mult.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_obi_interface.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_popcnt.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_prefetch_buffer.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_prefetch_controller.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_register_file_ff.sv
  /home/kersz/Documents/cv32e40p/bhv/cv32e40p_sim_clock_gate.sv
  /home/kersz/Documents/cv32e40p/rtl/cv32e40p_sleep_unit.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/src/fpnew_top.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/lzc.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv
  /home/kersz/Documents/cv32e40p/rtl/impl/axi_subsystem.sv
}
read_verilog -library xil_defaultlib {
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
  /home/kersz/Documents/cv32e40p/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
}
read_ip -quiet /home/kersz/Documents/cv32e40p/cv32e40p.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.gen/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.gen/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.gen/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc]

read_ip -quiet /home/kersz/Documents/cv32e40p/cv32e40p.srcs/sources_1/ip/dp_axi_bram/dp_axi_bram.xci
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.srcs/sources_1/ip/dp_axi_bram/dp_axi_bram_ooc.xdc]

read_ip -quiet /home/kersz/Documents/cv32e40p/cv32e40p.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.gen/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc]

read_ip -quiet /home/kersz/Documents/cv32e40p/cv32e40p.srcs/sources_1/ip/axi_to_bram/axi_to_bram.xci
set_property used_in_implementation false [get_files -all /home/kersz/Documents/cv32e40p/cv32e40p.gen/sources_1/ip/axi_to_bram/axi_to_bram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kersz/Documents/cv32e40p/constraints/Nexys-4-Master.xdc
set_property used_in_implementation false [get_files /home/kersz/Documents/cv32e40p/constraints/Nexys-4-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/kersz/Documents/cv32e40p/cv32e40p.srcs/utils_1/imports/synth_1/axi_subsystem.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top axi_subsystem -part xc7a100tcsg324-1 -flatten_hierarchy none -gated_clock_conversion auto
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_subsystem.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_subsystem_utilization_synth.rpt -pb axi_subsystem_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
