# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kersz/Documents/cv32e40p/constraints/Nexys-4-Master.xdc

# IP: ip/axi_uartlite_0/axi_uartlite_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uartlite_0 || ORIG_REF_NAME==axi_uartlite_0} -quiet] -quiet

# IP: ip/dp_axi_bram/dp_axi_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dp_axi_bram || ORIG_REF_NAME==dp_axi_bram} -quiet] -quiet

# IP: ip/axi_crossbar_0/axi_crossbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_crossbar_0 || ORIG_REF_NAME==axi_crossbar_0} -quiet] -quiet
